# Generated by Django 4.2.5 on 2023-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="women",
            options={
                "ordering": ["id"],
                "verbose_name": "ПРОДУКТ",
                "verbose_name_plural": "ПРОДУКТ",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="content",
            field=models.TextField(blank=True, verbose_name="ТЕКСТ (ОБЯСНЕНИЕ)"),
        ),
        migrations.AlterField(
            model_name="women",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="НАЗВАНИЕ В СЫЛЛКЕ"
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="women",
            name="title",
            field=models.CharField(max_length=255, verbose_name="НАЗВАНИЕ"),
        ),
    ]
